import React from 'react';
import { Helmet } from 'react-helmet';
import { useNavigate } from 'react-router-dom';
import { ChevronLeft } from 'lucide-react';
import { Button } from '@/components/ui/button';

const PrivacyPolicy = () => {
    const navigate = useNavigate();

    const PolicySection = ({ title, children }) => (
        <section className="mb-8">
            <h2 className="text-xl md:text-2xl font-bold text-gray-800 mb-4">{title}</h2>
            <div className="prose prose-sm md:prose-lg text-gray-600 max-w-none">{children}</div>
        </section>
    );

    return (
        <>
            <Helmet>
                <title>Privacy Policy - NetLife</title>
                <meta name="description" content="Privacy Policy for NetLife services." />
            </Helmet>

            {/* Mobile Layout */}
            <div className="block md:hidden bg-white min-h-screen">
                <div className="p-6">
                    <header className="flex items-center mb-6 -ml-2">
                        <Button variant="ghost" size="icon" onClick={() => navigate(-1)}>
                            <ChevronLeft size={24} />
                        </Button>
                        <h1 className="text-3xl font-bold text-gray-900 ml-2">Privacy Policy</h1>
                    </header>

                    <main className="pb-12">
                        <p className="text-sm text-gray-500 mb-6">Effective date: 2025-06-22</p>

                        <PolicySection title="1. Introduction">
                            <p>Welcome to NetLife. ("us", "we", or "our") operates the NetLife application (hereinafter referred to as "Service"). Our Privacy Policy governs your visit to and use of our Service, and explains how we collect, safeguard and disclose information that results from your use of our Service. We use your data to provide and improve Service. By using Service, you agree to the collection and use of information in accordance with this policy. Our Terms and Conditions ("Terms") govern all use of our Service and together with the Privacy Policy constitutes your agreement with us ("agreement").</p>
                        </PolicySection>

                        <PolicySection title="2. Definitions">
                            <p><strong>SERVICE</strong> means the NetLife application operated by Makerere University School of Public Health.</p>
                            <p><strong>PERSONAL DATA</strong> means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</p>
                            <p><strong>USAGE DATA</strong> is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).</p>
                            <p><strong>COOKIES</strong> are small files stored on your device (computer or mobile device) that help the Service function and remember your preferences.</p>
                        </PolicySection>

                        <PolicySection title="3. Information Collection and Use">
                            <p>We collect several different types of information for various purposes to provide and improve our Service to you. This includes data you provide directly, such as when you create a profile, and data collected automatically as you interact with the app. Our primary goal in collecting this information is to provide you with a secure, efficient, and personalized experience. We are committed to the principle of data minimization, meaning we only collect data that is necessary to fulfill the specific purposes of the Service, such as facilitating health service requests, providing personalized health information, and ensuring the security and integrity of your account. All data collection is performed with your consent and for legitimate operational purposes.</p>
                        </PolicySection>

                        <PolicySection title="4. Types of Data Collected">
                            <p><strong>Personal Data:</strong> While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. This may include, but is not limited to: your phone number, date of birth, gender, and location details like district. This information is essential for creating your unique, secure profile and for tailoring health services to your specific needs. We treat this data with the highest level of confidentiality and use it strictly for the purpose of delivering our services, such as connecting you with healthcare providers or delivering health products. You have control over your profile and can manage your personal data within the app's account settings.</p>
                            <p><strong>Usage Data:</strong> We may collect information that your device sends whenever you use our Service. This Usage Data may include information such as your device's Internet Protocol address (e.g. IP address), device type, operating system version, the features of our Service that you visit, the time and date of your visit, the time spent on those features, and other diagnostic data. This information is aggregated and anonymized wherever possible. We use this data to understand how our Service is used, to monitor for security threats, to identify and fix bugs, and to improve the overall performance and usability of the application, ensuring it remains reliable and effective for all our users.</p>
                            <p><strong>Location Data:</strong> We may use and store information about your location if you give us permission to do so. We use this data to provide features of our Service, such as finding nearby health facilities or for the delivery of products and services. You can enable or disable location services when you use our Service at any time through your device settings. We only request location data when it is necessary for a specific feature you have chosen to use, such as requesting a home delivery. This data is not tracked continuously and is only used for the specific, in-the-moment purpose for which it was collected, ensuring your privacy is respected while providing location-based convenience.</p>
                            <p><strong>Tracking Cookies Data:</strong> We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information. Cookies are files with a small amount of data which may include an anonymous unique identifier. They are sent to your device from the app and stored on your device. We use "session cookies" to operate our Service, which are temporary and deleted when you close the app. We also use "preference cookies" to remember your settings and various preferences, such as your chosen language or avatar, so you don't have to re-enter them each time. Finally, "security cookies" are used for security purposes, such as authenticating your session and protecting your account from unauthorized access. You can control the use of cookies at the device level, but if you choose to disable them, some features of our Service may not function properly. Our use of cookies is designed to enhance your user experience and maintain the security of your account.</p>
                        </PolicySection>

                        <PolicySection title="5. Use of Data">
                            <p>NetLife uses the collected data for various purposes:</p>
                            <ul>
                                <li className="mb-2">To provide and maintain our Service, including monitoring its usage and performance.</li>
                                <li className="mb-2">To manage your account and your registration as a user of the Service. The Personal Data you provide can give you access to different functionalities of the Service that are available to you as a registered user.</li>
                                <li className="mb-2">To facilitate the delivery of health services and products you request, including sharing necessary details with trusted health partners under strict confidentiality agreements.</li>
                                <li className="mb-2">To notify you about changes to our Service or policies.</li>
                                <li className="mb-2">To allow you to participate in interactive features of our Service when you choose to do so.</li>
                                <li className="mb-2">To provide customer support and respond to your inquiries.</li>
                                <li className="mb-2">To gather analysis or valuable information so that we can improve our Service. This includes analyzing trends and user behavior to enhance features and usability.</li>
                                <li className="mb-2">To detect, prevent and address technical issues, fraud, or security risks.</li>
                                <li className="mb-2">To fulfill any other purpose for which you provide it, with your explicit consent.</li>
                                <li className="mb-2">To carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection.</li>
                            </ul>
                        </PolicySection>

                        <PolicySection title="6. Retention of Data">
                            <p>We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies. We also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.</p>
                        </PolicySection>

                        <PolicySection title="7. Transfer of Data">
                            <p>Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction. Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer. NetLife will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.</p>
                        </PolicySection>

                        <PolicySection title="8. Disclosure of Data">
                            <p>We may disclose personal information that we collect, or you provide:</p>
                            <ul>
                                <li className="mb-2"><strong>Disclosure for Law Enforcement:</strong> Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities.</li>
                                <li className="mb-2"><strong>Business Transaction:</strong> If we or our subsidiaries are involved in a merger, acquisition or asset sale, your Personal Data may be transferred.</li>
                                <li className="mb-2"><strong>With Service Providers:</strong> We may share your information with trusted third-party service providers to facilitate our Service, such as healthcare partners for service delivery. These parties are contractually obligated to keep your information confidential and use it only for the purposes for which we disclose it to them.</li>
                                <li className="mb-2"><strong>With Your Consent:</strong> We may disclose your personal information for any other purpose with your explicit consent. We will not share your sensitive health information without a clear, affirmative action from you for a specified purpose.</li>
                            </ul>
                        </PolicySection>

                        <PolicySection title="9. Security of Data">
                            <p>The security of your data is a top priority for us. We use a variety of administrative, technical, and physical security measures to protect your personal information. This includes end-to-end encryption for data in transit and encryption for data at rest. We restrict access to personal data to authorized personnel only, who are bound by strict confidentiality obligations. While we strive to use commercially acceptable means to protect your Personal Data, remember that no method of transmission over the Internet or method of electronic storage is 100% secure. We are continuously working to improve our security protocols to safeguard your information against unauthorized access, use, or disclosure.</p>
                        </PolicySection>

                        <PolicySection title="10. Your Data Protection Rights Under General Data Protection Regulation (GDPR)">
                            <p>If you are a resident of the European Union (EU) and European Economic Area (EEA), you have certain data protection rights, covered by GDPR. We aim to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data. You have the right to access, update or to delete the information we have on you; the right of rectification; the right to object; the right of restriction; the right to data portability; and the right to withdraw consent. Please note that we may ask you to verify your identity before responding to such requests. You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the EEA.</p>
                        </PolicySection>

                        <PolicySection title="11. Your Data Protection Rights under the California Privacy Protection Act (CalOPPA)">
                            <p>CalOPPA is the first state law in the nation to require commercial websites and online services to post a privacy policy. Our policy complies with CalOPPA by: identifying the categories of Personally Identifiable Information (PII) that are collected and the third parties with whom it may be shared; providing a clear and conspicuous link to this policy; and describing any process for you to review and request changes to your PII. We also inform you of how we respond to "Do Not Track" signals. We do not track our users over time and across third-party websites to provide targeted advertising and therefore do not respond to Do Not Track (DNT) signals. We also do not authorize the collection of PII from our Service for third-party use through advertising technologies.</p>
                        </PolicySection>

                        <PolicySection title="12. Your Data Protection Rights under the California Consumer Privacy Act (CCPA)">
                            <p>If you are a California resident, you are entitled to learn what data we collect about you, ask to delete your data and not to sell (or share) it. To exercise your data protection rights, you can make certain requests. You have the right to know what personal information we have collected about you, the sources from which it is collected, and the purposes for collecting it. You have the right to request the deletion of your personal information, subject to certain exceptions. You also have the right to opt-out of the sale of your personal information. NetLife does not sell your personal information. You have the right to non-discrimination for exercising your consumer privacy rights. To make a request, please contact us. We will verify your request and process it within the timeframes stipulated by the CCPA.</p>
                        </PolicySection>

                        <PolicySection title="13. Service Providers">
                            <p>We may employ third-party companies and individuals to facilitate our Service ("Service Providers"), provide Service on our behalf, perform Service-related services, or assist us in analyzing how our Service is used. These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose. All our Service Providers are vetted for their security and privacy practices and are bound by strict data processing agreements that ensure they handle your data with the same level of care that we do. This includes healthcare partners, technology infrastructure providers, and customer support tools that help us deliver a seamless and secure experience.</p>
                        </PolicySection>

                        <PolicySection title="14. Analytics">
                            <p>We may use third-party Service Providers to monitor and analyze the use of our Service. This is done to understand usage patterns and improve the app's functionality. All data sent to analytics services is anonymized to protect your identity.</p>
                        </PolicySection>

                        <PolicySection title="15. CI/CD tools">
                            <p>We may use third-party Service Providers to automate the development and deployment process of our Service. These tools help us build, test, and release updates efficiently and securely, but they do not have access to your Personal Data.</p>
                        </PolicySection>

                        <PolicySection title="16. Advertising">
                            <p>We do not display third-party advertisements in our Service. We will not use your Personal Data for advertising purposes or share it with advertisers.</p>
                        </PolicySection>

                        <PolicySection title="17. Behavioral Remarketing">
                            <p>NetLife does not use remarketing services to advertise on third-party websites to you after you visited our Service. We believe in protecting your privacy, and that includes not tracking your activity across the web for marketing purposes. Your interactions within the NetLife app are confidential and are not used to target you with ads elsewhere. Our focus is solely on providing you with health services in a secure and private environment, free from the influence of external advertising and tracking. We are committed to this principle to maintain the trust you place in us with your sensitive information.</p>
                        </PolicySection>

                        <PolicySection title="18. Payments">
                            <p>We may provide paid products and/or services within Service. In that case, we use third-party services for payment processing (e.g. payment processors). We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, Mastercard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information, providing a robust and secure environment for all transactions conducted through our Service.</p>
                        </PolicySection>

                        <PolicySection title="19. Links to Other Sites">
                            <p>Our Service may contain links to other sites that are not operated by us. If you click a third-party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit. We have no control over and assume no responsibility for the content, privacy policies or practices of any third-party sites or services. These links may be provided for informational purposes, such as linking to a public health resource or a partner facility's website. While we strive to link only to reputable sources, their data practices are outside of our control. Your interaction with any other website is subject to that website's own rules and policies. Therefore, we encourage you to be cautious and read the privacy statements of any other site that collects personally identifiable information.</p>
                        </PolicySection>

                        <PolicySection title="20. Children's Privacy">
                            <p>Our Services are not intended for use by children under the age of 15 ("Child" or "Children"). We do not knowingly collect personally identifiable information from Children under 15. If you become aware that a Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from Children without verification of parental consent, we take steps to remove that information from our servers. Our age verification processes are designed to prevent underage use and protect the privacy of minors.</p>
                        </PolicySection>

                        <PolicySection title="21. Changes to This Privacy Policy">
                            <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page. We will let you know via a prominent notice within our Service, prior to the change becoming effective and update the "effective date" at the top of this Privacy Policy. You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page. Your continued use of the Service after we post any modifications to the Privacy Policy on this page will constitute your acknowledgment of the modifications and your consent to abide and be bound by the modified Privacy Policy.</p>
                        </PolicySection>

                        <PolicySection title="22. Contact Us">
                            <p>If you have any questions about this Privacy Policy, please contact us by email: <a href="mailto:info@netlife.cc" className="text-primary hover:underline">info@netlife.cc</a>.</p>
                        </PolicySection>
                    </main>
                </div>
            </div>

            {/* Desktop Layout */}
            <div className="hidden md:block bg-white min-h-screen">
                <div className="max-w-4xl mx-auto px-8 py-12">
                    <header className="flex items-center mb-8">
                        <Button variant="ghost" size="icon" onClick={() => navigate(-1)} className="mr-4">
                            <ChevronLeft size={24} />
                        </Button>
                        <div>
                            <h1 className="text-4xl font-bold text-gray-900">Privacy Policy</h1>
                            <p className="text-sm text-gray-500 mt-2">Effective date: 2025-06-22</p>
                        </div>
                    </header>

                    <main className="prose prose-lg max-w-none">
                        <PolicySection title="1. Introduction">
                            <p>Welcome to NetLife. ("us", "we", or "our") operates the NetLife application (hereinafter referred to as "Service"). Our Privacy Policy governs your visit to and use of our Service, and explains how we collect, safeguard and disclose information that results from your use of our Service. We use your data to provide and improve Service. By using Service, you agree to the collection and use of information in accordance with this policy. Our Terms and Conditions ("Terms") govern all use of our Service and together with the Privacy Policy constitutes your agreement with us ("agreement").</p>
                        </PolicySection>

                        <PolicySection title="2. Definitions">
                            <p><strong>SERVICE</strong> means the NetLife application operated by Makerere University School of Public Health.</p>
                            <p><strong>PERSONAL DATA</strong> means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</p>
                            <p><strong>USAGE DATA</strong> is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).</p>
                            <p><strong>COOKIES</strong> are small files stored on your device (computer or mobile device) that help the Service function and remember your preferences.</p>
                        </PolicySection>

                        <PolicySection title="3. Information Collection and Use">
                            <p>We collect several different types of information for various purposes to provide and improve our Service to you. This includes data you provide directly, such as when you create a profile, and data collected automatically as you interact with the app. Our primary goal in collecting this information is to provide you with a secure, efficient, and personalized experience. We are committed to the principle of data minimization, meaning we only collect data that is necessary to fulfill the specific purposes of the Service, such as facilitating health service requests, providing personalized health information, and ensuring the security and integrity of your account. All data collection is performed with your consent and for legitimate operational purposes.</p>
                        </PolicySection>

                        <PolicySection title="4. Types of Data Collected">
                            <p><strong>Personal Data:</strong> While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. This may include, but is not limited to: your phone number, date of birth, gender, and location details like district. This information is essential for creating your unique, secure profile and for tailoring health services to your specific needs. We treat this data with the highest level of confidentiality and use it strictly for the purpose of delivering our services, such as connecting you with healthcare providers or delivering health products. You have control over your profile and can manage your personal data within the app's account settings.</p>
                            <p><strong>Usage Data:</strong> We may collect information that your device sends whenever you use our Service. This Usage Data may include information such as your device's Internet Protocol address (e.g. IP address), device type, operating system version, the features of our Service that you visit, the time and date of your visit, the time spent on those features, and other diagnostic data. This information is aggregated and anonymized wherever possible. We use this data to understand how our Service is used, to monitor for security threats, to identify and fix bugs, and to improve the overall performance and usability of the application, ensuring it remains reliable and effective for all our users.</p>
                            <p><strong>Location Data:</strong> We may use and store information about your location if you give us permission to do so. We use this data to provide features of our Service, such as finding nearby health facilities or for the delivery of products and services. You can enable or disable location services when you use our Service at any time through your device settings. We only request location data when it is necessary for a specific feature you have chosen to use, such as requesting a home delivery. This data is not tracked continuously and is only used for the specific, in-the-moment purpose for which it was collected, ensuring your privacy is respected while providing location-based convenience.</p>
                            <p><strong>Tracking Cookies Data:</strong> We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information. Cookies are files with a small amount of data which may include an anonymous unique identifier. They are sent to your device from the app and stored on your device. We use "session cookies" to operate our Service, which are temporary and deleted when you close the app. We also use "preference cookies" to remember your settings and various preferences, such as your chosen language or avatar, so you don't have to re-enter them each time. Finally, "security cookies" are used for security purposes, such as authenticating your session and protecting your account from unauthorized access. You can control the use of cookies at the device level, but if you choose to disable them, some features of our Service may not function properly. Our use of cookies is designed to enhance your user experience and maintain the security of your account.</p>
                        </PolicySection>

                        <PolicySection title="5. Use of Data">
                            <p>NetLife uses the collected data for various purposes:</p>
                            <ul>
                                <li className="mb-2">To provide and maintain our Service, including monitoring its usage and performance.</li>
                                <li className="mb-2">To manage your account and your registration as a user of the Service. The Personal Data you provide can give you access to different functionalities of the Service that are available to you as a registered user.</li>
                                <li className="mb-2">To facilitate the delivery of health services and products you request, including sharing necessary details with trusted health partners under strict confidentiality agreements.</li>
                                <li className="mb-2">To notify you about changes to our Service or policies.</li>
                                <li className="mb-2">To allow you to participate in interactive features of our Service when you choose to do so.</li>
                                <li className="mb-2">To provide customer support and respond to your inquiries.</li>
                                <li className="mb-2">To gather analysis or valuable information so that we can improve our Service. This includes analyzing trends and user behavior to enhance features and usability.</li>
                                <li className="mb-2">To detect, prevent and address technical issues, fraud, or security risks.</li>
                                <li className="mb-2">To fulfill any other purpose for which you provide it, with your explicit consent.</li>
                                <li className="mb-2">To carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection.</li>
                            </ul>
                        </PolicySection>

                        <PolicySection title="6. Retention of Data">
                            <p>We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies. We also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.</p>
                        </PolicySection>

                        <PolicySection title="7. Transfer of Data">
                            <p>Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction. Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer. NetLife will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.</p>
                        </PolicySection>

                        <PolicySection title="8. Disclosure of Data">
                            <p>We may disclose personal information that we collect, or you provide:</p>
                            <ul>
                                <li className="mb-2"><strong>Disclosure for Law Enforcement:</strong> Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities.</li>
                                <li className="mb-2"><strong>Business Transaction:</strong> If we or our subsidiaries are involved in a merger, acquisition or asset sale, your Personal Data may be transferred.</li>
                                <li className="mb-2"><strong>With Service Providers:</strong> We may share your information with trusted third-party service providers to facilitate our Service, such as healthcare partners for service delivery. These parties are contractually obligated to keep your information confidential and use it only for the purposes for which we disclose it to them.</li>
                                <li className="mb-2"><strong>With Your Consent:</strong> We may disclose your personal information for any other purpose with your explicit consent. We will not share your sensitive health information without a clear, affirmative action from you for a specified purpose.</li>
                            </ul>
                        </PolicySection>

                        <PolicySection title="9. Security of Data">
                            <p>The security of your data is a top priority for us. We use a variety of administrative, technical, and physical security measures to protect your personal information. This includes end-to-end encryption for data in transit and encryption for data at rest. We restrict access to personal data to authorized personnel only, who are bound by strict confidentiality obligations. While we strive to use commercially acceptable means to protect your Personal Data, remember that no method of transmission over the Internet or method of electronic storage is 100% secure. We are continuously working to improve our security protocols to safeguard your information against unauthorized access, use, or disclosure.</p>
                        </PolicySection>

                        <PolicySection title="10. Your Data Protection Rights Under General Data Protection Regulation (GDPR)">
                            <p>If you are a resident of the European Union (EU) and European Economic Area (EEA), you have certain data protection rights, covered by GDPR. We aim to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data. You have the right to access, update or to delete the information we have on you; the right of rectification; the right to object; the right of restriction; the right to data portability; and the right to withdraw consent. Please note that we may ask you to verify your identity before responding to such requests. You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the EEA.</p>
                        </PolicySection>

                        <PolicySection title="11. Your Data Protection Rights under the California Privacy Protection Act (CalOPPA)">
                            <p>CalOPPA is the first state law in the nation to require commercial websites and online services to post a privacy policy. Our policy complies with CalOPPA by: identifying the categories of Personally Identifiable Information (PII) that are collected and the third parties with whom it may be shared; providing a clear and conspicuous link to this policy; and describing any process for you to review and request changes to your PII. We also inform you of how we respond to "Do Not Track" signals. We do not track our users over time and across third-party websites to provide targeted advertising and therefore do not respond to Do Not Track (DNT) signals. We also do not authorize the collection of PII from our Service for third-party use through advertising technologies.</p>
                        </PolicySection>

                        <PolicySection title="12. Your Data Protection Rights under the California Consumer Privacy Act (CCPA)">
                            <p>If you are a California resident, you are entitled to learn what data we collect about you, ask to delete your data and not to sell (or share) it. To exercise your data protection rights, you can make certain requests. You have the right to know what personal information we have collected about you, the sources from which it is collected, and the purposes for collecting it. You have the right to request the deletion of your personal information, subject to certain exceptions. You also have the right to opt-out of the sale of your personal information. NetLife does not sell your personal information. You have the right to non-discrimination for exercising your consumer privacy rights. To make a request, please contact us. We will verify your request and process it within the timeframes stipulated by the CCPA.</p>
                        </PolicySection>

                        <PolicySection title="13. Service Providers">
                            <p>We may employ third-party companies and individuals to facilitate our Service ("Service Providers"), provide Service on our behalf, perform Service-related services, or assist us in analyzing how our Service is used. These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose. All our Service Providers are vetted for their security and privacy practices and are bound by strict data processing agreements that ensure they handle your data with the same level of care that we do. This includes healthcare partners, technology infrastructure providers, and customer support tools that help us deliver a seamless and secure experience.</p>
                        </PolicySection>

                        <PolicySection title="14. Analytics">
                            <p>We may use third-party Service Providers to monitor and analyze the use of our Service. This is done to understand usage patterns and improve the app's functionality. All data sent to analytics services is anonymized to protect your identity.</p>
                        </PolicySection>

                        <PolicySection title="15. CI/CD tools">
                            <p>We may use third-party Service Providers to automate the development and deployment process of our Service. These tools help us build, test, and release updates efficiently and securely, but they do not have access to your Personal Data.</p>
                        </PolicySection>

                        <PolicySection title="16. Advertising">
                            <p>We do not display third-party advertisements in our Service. We will not use your Personal Data for advertising purposes or share it with advertisers.</p>
                        </PolicySection>

                        <PolicySection title="17. Behavioral Remarketing">
                            <p>NetLife does not use remarketing services to advertise on third-party websites to you after you visited our Service. We believe in protecting your privacy, and that includes not tracking your activity across the web for marketing purposes. Your interactions within the NetLife app are confidential and are not used to target you with ads elsewhere. Our focus is solely on providing you with health services in a secure and private environment, free from the influence of external advertising and tracking. We are committed to this principle to maintain the trust you place in us with your sensitive information.</p>
                        </PolicySection>

                        <PolicySection title="18. Payments">
                            <p>We may provide paid products and/or services within Service. In that case, we use third-party services for payment processing (e.g. payment processors). We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, Mastercard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information, providing a robust and secure environment for all transactions conducted through our Service.</p>
                        </PolicySection>

                        <PolicySection title="19. Links to Other Sites">
                            <p>Our Service may contain links to other sites that are not operated by us. If you click a third-party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit. We have no control over and assume no responsibility for the content, privacy policies or practices of any third-party sites or services. These links may be provided for informational purposes, such as linking to a public health resource or a partner facility's website. While we strive to link only to reputable sources, their data practices are outside of our control. Your interaction with any other website is subject to that website's own rules and policies. Therefore, we encourage you to be cautious and read the privacy statements of any other site that collects personally identifiable information.</p>
                        </PolicySection>

                        <PolicySection title="20. Children's Privacy">
                            <p>Our Services are not intended for use by children under the age of 15 ("Child" or "Children"). We do not knowingly collect personally identifiable information from Children under 15. If you become aware that a Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from Children without verification of parental consent, we take steps to remove that information from our servers. Our age verification processes are designed to prevent underage use and protect the privacy of minors.</p>
                        </PolicySection>

                        <PolicySection title="21. Changes to This Privacy Policy">
                            <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page. We will let you know via a prominent notice within our Service, prior to the change becoming effective and update the "effective date" at the top of this Privacy Policy. You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page. Your continued use of the Service after we post any modifications to the Privacy Policy on this page will constitute your acknowledgment of the modifications and your consent to abide and be bound by the modified Privacy Policy.</p>
                        </PolicySection>

                        <PolicySection title="22. Contact Us">
                            <p>If you have any questions about this Privacy Policy, please contact us by email: <a href="mailto:info@netlife.cc" className="text-primary hover:underline">info@netlife.cc</a>.</p>
                        </PolicySection>
                    </main>
                </div>
            </div>
        </>
    );
};

export default PrivacyPolicy;