name: Deploy

on:
  push:
    branches:
      - dev

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        working-directory: ./
        run: npm install --force

      - name: Building project
        working-directory: ./
        run: npm run build
        env:
         CI: false
         VITE_API_URL: ${{ secrets.VITE_GOOGLE_MAPS_API_KEY }}
         VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
         VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
      - name: Deploying
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_dev_username }}
          password: ${{ secrets.ftp_dev_password }}
          local-dir: ./dist/
          protocol: ftp  
          
